[package]
name = "ferrosa-index"
version = "1.0.0-beta.1"
edition = "2021"

[dependencies]
ferrosa-common = { path = "../ferrosa-common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bitflags = "2"
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "2"
rand = "0.8"

[dev-dependencies]
tempfile = "3"
