//! Cassandra compatibility tests — read SSTable fixtures generated by Cassandra.
//!
//! These tests read BTI SSTables produced by `tools/generate_sstable_fixtures.java`
//! and verify Ferrosa can correctly parse all component files. The fixture data
//! uses the schema:
//!
//!     CREATE TABLE test.fixture (pk text, ck int, val text, PRIMARY KEY (pk, ck))
//!
//! Fixture directories live under `tests/fixtures/` with standardized component
//! file names (Data.db, Partitions.db, etc.).

use std::fs;
use std::path::{Path, PathBuf};

use ferrosa_common::{DecoratedKey, PartitionKey};
use ferrosa_sstable::reader::{SSTableComponents, SSTableReader};
use ferrosa_sstable::statistics::read_statistics;
use ferrosa_sstable::toc;

/// Find the fixture directory, returning None if fixtures haven't been generated yet.
fn fixture_dir(name: &str) -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    if dir.exists() {
        Some(dir)
    } else {
        None
    }
}

/// Load a component file from the fixture directory, returning its bytes.
fn load_component(dir: &Path, suffix: &str) -> Vec<u8> {
    let path = dir.join(suffix);
    fs::read(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e))
}

/// Open an SSTableReader from a fixture directory.
fn open_fixture(dir: &Path) -> SSTableReader<Vec<u8>> {
    let data = load_component(dir, "Data.db");
    let partitions = load_component(dir, "Partitions.db");
    let rows = load_component(dir, "Rows.db");
    let filter = load_component(dir, "Filter.db");
    let statistics = load_component(dir, "Statistics.db");
    let compression_info_path = dir.join("CompressionInfo.db");
    let compression_info = if compression_info_path.exists() {
        Some(fs::read(&compression_info_path).unwrap())
    } else {
        None
    };

    let components = SSTableComponents {
        data,
        partitions,
        rows,
        filter,
        compression_info,
        statistics,
    };

    SSTableReader::open(components).expect("Failed to open SSTable fixture")
}

#[test]
fn read_multi_partition_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: multi_partition fixture not generated. Run tools/generate_sstable_fixtures.java");
        return;
    };

    let reader = open_fixture(&dir);

    // Fixture has 5 partitions: alpha, bravo, charlie, delta, echo
    assert_eq!(reader.key_count(), 5, "expected 5 partitions");

    // Look up each known partition key
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let partition = match reader.get_partition(&dk) {
            Ok(p) => p,
            Err(e) => panic!("Error looking up {}: {}", pk_str, e),
        };
        assert!(
            partition.is_some(),
            "Partition {} should exist in fixture",
            pk_str
        );
        let partition = partition.unwrap();
        eprintln!(
            "Partition {}: key={:?}, deletion={{marked_for_delete_at={}, local_deletion_time={}}}, rows={}",
            pk_str,
            String::from_utf8_lossy(partition.key.key.as_bytes()),
            partition.deletion.marked_for_delete_at,
            partition.deletion.local_deletion_time,
            partition.rows.len()
        );
        assert_eq!(partition.key.key.as_bytes(), pk_str.as_bytes());
        assert!(partition.deletion.is_live());
        assert!(!partition.rows.is_empty(), "{} should have rows", pk_str);
    }
}

#[test]
fn read_single_partition_fixture() {
    let Some(dir) = fixture_dir("single_partition") else {
        eprintln!("Skipping: single_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"only-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'only-pk' should exist");
    let partition = partition.unwrap();
    assert_eq!(partition.rows.len(), 1, "should have exactly 1 row");
}

#[test]
fn read_wide_partition_fixture() {
    let Some(dir) = fixture_dir("wide_partition") else {
        eprintln!("Skipping: wide_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"wide-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'wide-pk' should exist");
    let partition = partition.unwrap();
    assert!(
        partition.rows.len() >= 50,
        "wide partition should have 50+ rows, got {}",
        partition.rows.len()
    );
}

#[test]
fn read_toc_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: TOC fixture not generated");
        return;
    };

    let toc_bytes = load_component(&dir, "TOC.txt");
    let entries = toc::read_toc(&toc_bytes).unwrap();
    assert!(entries.len() >= 6, "TOC should list at least 6 components");
}

#[test]
fn read_statistics_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: Statistics fixture not generated");
        return;
    };

    let stats_bytes = load_component(&dir, "Statistics.db");
    let stats = read_statistics(&stats_bytes).unwrap();

    assert_eq!(
        stats.validation.partitioner_class,
        "org.apache.cassandra.dht.Murmur3Partitioner"
    );
    assert!(
        stats.validation.bloom_fp_chance > 0.0 && stats.validation.bloom_fp_chance < 1.0,
        "bloom FP chance should be between 0 and 1"
    );

    // Header should have column definitions matching our schema
    assert_eq!(
        stats.header.clustering_types.len(),
        1,
        "1 clustering column (ck int)"
    );
    assert_eq!(
        stats.header.regular_columns.len(),
        1,
        "1 regular column (val text)"
    );
}

#[test]
/// Write-read roundtrip: ferrosa writer produces SSTables that ferrosa reader
/// can parse, for all cell types (normal, tombstone, expiring/TTL).
/// This validates the wire format matches Cassandra's Cell.Serializer spec.
fn ferrosa_write_read_roundtrip_all_cell_types() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: 0,
        min_ttl: 0,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec!["org.apache.cassandra.db.marshal.Int32Type".into()],
        static_columns: vec![],
        regular_columns: vec![(
            b"val".to_vec(),
            "org.apache.cassandra.db.marshal.UTF8Type".into(),
        )],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
    };

    let timestamp = 1_000_100i64;

    // Three partitions: normal cell, tombstone cell, expiring cell (TTL)
    let partitions = vec![
        // 1. Normal cell
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"normal".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 1], // ck = 1
                cells: vec![(0, CellValue::live(b"hello".to_vec(), timestamp))],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
        // 2. Tombstone cell
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"tombstone".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 2],
                cells: vec![(0, CellValue::tombstone(timestamp, 1_700_000))],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
        // 3. Expiring cell (USING TTL 3600)
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"ttl_cell".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 3],
                cells: vec![(
                    0,
                    CellValue::expiring(b"expires".to_vec(), timestamp, 3600, 1_700_000),
                )],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
    ];

    let mut writer = SSTableWriter::new(options, header.clone());
    for p in &partitions {
        writer.add_partition(p).unwrap();
    }
    let output = writer.finish().unwrap();

    // Read back and verify each partition
    let mut reader = DataReader::new(&output.data, &header, 0);

    // 1. Normal cell
    let p = reader.read_partition().unwrap().expect("normal partition");
    assert_eq!(p.key.key.as_bytes(), b"normal");
    let cell = &p.rows[0].cells[0].1;
    assert!(!cell.is_tombstone());
    assert_eq!(
        cell.ttl,
        ferrosa_common::NO_TTL,
        "normal cell should have no TTL"
    );
    assert_eq!(cell.value.as_deref(), Some(b"hello".as_slice()));

    // 2. Tombstone cell
    let p = reader
        .read_partition()
        .unwrap()
        .expect("tombstone partition");
    assert_eq!(p.key.key.as_bytes(), b"tombstone");
    let cell = &p.rows[0].cells[0].1;
    assert!(cell.is_tombstone());
    assert_eq!(cell.timestamp, timestamp);
    assert_eq!(cell.local_deletion_time, 1_700_000);
    assert!(cell.value.is_none());

    // 3. Expiring cell
    let p = reader.read_partition().unwrap().expect("ttl partition");
    assert_eq!(p.key.key.as_bytes(), b"ttl_cell");
    let cell = &p.rows[0].cells[0].1;
    assert!(!cell.is_tombstone(), "expiring cell is not a tombstone");
    assert_eq!(cell.ttl, 3600, "TTL must survive roundtrip");
    assert_eq!(
        cell.local_deletion_time, 1_700_000,
        "LDT must survive roundtrip"
    );
    assert_eq!(cell.value.as_deref(), Some(b"expires".as_slice()));

    // No more partitions
    assert!(reader.read_partition().unwrap().is_none());
}

#[test]
/// Read SSTable fixtures generated by Cassandra's CQLSSTableWriter.
/// These test that ferrosa can read SSTables produced by real Cassandra code.
/// Run `tests/sstable-compat/generate.sh` to create the fixtures.
fn read_cassandra_generated_normal_cells() {
    let Some(dir) = fixture_dir("cassandra_generated/normal_cells") else {
        eprintln!(
            "Skipping: Cassandra-generated fixtures not found. Run tests/sstable-compat/generate.sh"
        );
        return;
    };

    // Find the actual SSTable directory (Cassandra puts them in a subdirectory)
    let sstable_dirs: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();

    if sstable_dirs.is_empty() {
        // Files might be directly in the directory
        let reader = open_fixture(&dir);
        assert!(
            reader.key_count() >= 3,
            "expected at least 3 partitions (alpha, bravo, charlie)"
        );
    } else {
        // Cassandra nests SSTables in subdirectories
        for sub in sstable_dirs {
            let path = sub.path();
            if std::fs::read_dir(&path).unwrap().any(|e| {
                e.unwrap()
                    .file_name()
                    .to_string_lossy()
                    .ends_with("-Data.db")
            }) {
                eprintln!("Reading Cassandra SSTable from {:?}", path);
                // TODO: Cassandra uses different file naming (e.g., nb-1-big-Data.db)
                // Need to adapt the reader for Cassandra's file naming convention
            }
        }
    }
}

#[test]
fn read_cassandra_generated_ttl_cells() {
    let Some(dir) = fixture_dir("cassandra_generated/ttl_cells") else {
        eprintln!(
            "Skipping: Cassandra TTL fixtures not found. Run tests/sstable-compat/generate.sh"
        );
        return;
    };

    // When fixtures exist, verify expiring cells are parsed with correct TTL
    eprintln!("Cassandra TTL fixture directory exists at {:?}", dir);
    // Full parsing test will be added once fixture naming is standardized
}

#[test]
fn bloom_filter_matches_fixture_keys() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: bloom filter fixture test not generated");
        return;
    };

    let reader = open_fixture(&dir);

    // All inserted keys must pass the bloom filter (no false negatives)
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let (h1, h2) = dk.filter_hash();
        assert!(
            reader.bloom_filter().is_present(h1, h2),
            "Bloom filter must not have false negatives for {}",
            pk_str
        );
    }
}
