//! Cassandra compatibility tests — read SSTable fixtures generated by Cassandra.
//!
//! These tests read BTI SSTables produced by `tools/generate_sstable_fixtures.java`
//! and verify Ferrosa can correctly parse all component files. The fixture data
//! uses the schema:
//!
//!     CREATE TABLE test.fixture (pk text, ck int, val text, PRIMARY KEY (pk, ck))
//!
//! Fixture directories live under `tests/fixtures/` with standardized component
//! file names (Data.db, Partitions.db, etc.).

use std::fs;
use std::path::{Path, PathBuf};

use ferrosa_common::{DecoratedKey, PartitionKey};
use ferrosa_sstable::reader::{SSTableComponents, SSTableReader};
use ferrosa_sstable::statistics::read_statistics;
use ferrosa_sstable::toc;

/// Find the fixture directory, returning None if fixtures haven't been generated yet.
fn fixture_dir(name: &str) -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    if dir.exists() {
        Some(dir)
    } else {
        None
    }
}

/// Load a component file from the fixture directory, returning its bytes.
fn load_component(dir: &Path, suffix: &str) -> Vec<u8> {
    let path = dir.join(suffix);
    fs::read(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e))
}

/// Open an SSTableReader from a fixture directory.
fn open_fixture(dir: &Path) -> SSTableReader<Vec<u8>> {
    let data = load_component(dir, "Data.db");
    let partitions = load_component(dir, "Partitions.db");
    let rows = load_component(dir, "Rows.db");
    let filter = load_component(dir, "Filter.db");
    let statistics = load_component(dir, "Statistics.db");
    let compression_info_path = dir.join("CompressionInfo.db");
    let compression_info = if compression_info_path.exists() {
        Some(fs::read(&compression_info_path).unwrap())
    } else {
        None
    };

    let components = SSTableComponents {
        data,
        partitions,
        rows,
        filter,
        compression_info,
        statistics,
    };

    SSTableReader::open(components).expect("Failed to open SSTable fixture")
}

#[test]
fn read_multi_partition_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: multi_partition fixture not generated. Run tools/generate_sstable_fixtures.java");
        return;
    };

    let reader = open_fixture(&dir);

    // Fixture has 5 partitions: alpha, bravo, charlie, delta, echo
    assert_eq!(reader.key_count(), 5, "expected 5 partitions");

    // Look up each known partition key
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let partition = match reader.get_partition(&dk) {
            Ok(p) => p,
            Err(e) => panic!("Error looking up {}: {}", pk_str, e),
        };
        assert!(
            partition.is_some(),
            "Partition {} should exist in fixture",
            pk_str
        );
        let partition = partition.unwrap();
        eprintln!(
            "Partition {}: key={:?}, deletion={{marked_for_delete_at={}, local_deletion_time={}}}, rows={}",
            pk_str,
            String::from_utf8_lossy(partition.key.key.as_bytes()),
            partition.deletion.marked_for_delete_at,
            partition.deletion.local_deletion_time,
            partition.rows.len()
        );
        assert_eq!(partition.key.key.as_bytes(), pk_str.as_bytes());
        assert!(partition.deletion.is_live());
        assert!(!partition.rows.is_empty(), "{} should have rows", pk_str);
    }
}

#[test]
fn read_single_partition_fixture() {
    let Some(dir) = fixture_dir("single_partition") else {
        eprintln!("Skipping: single_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"only-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'only-pk' should exist");
    let partition = partition.unwrap();
    assert_eq!(partition.rows.len(), 1, "should have exactly 1 row");
}

#[test]
fn read_wide_partition_fixture() {
    let Some(dir) = fixture_dir("wide_partition") else {
        eprintln!("Skipping: wide_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"wide-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'wide-pk' should exist");
    let partition = partition.unwrap();
    assert!(
        partition.rows.len() >= 50,
        "wide partition should have 50+ rows, got {}",
        partition.rows.len()
    );
}

#[test]
fn read_toc_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: TOC fixture not generated");
        return;
    };

    let toc_bytes = load_component(&dir, "TOC.txt");
    let entries = toc::read_toc(&toc_bytes).unwrap();
    assert!(entries.len() >= 6, "TOC should list at least 6 components");
}

#[test]
fn read_statistics_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: Statistics fixture not generated");
        return;
    };

    let stats_bytes = load_component(&dir, "Statistics.db");
    let stats = read_statistics(&stats_bytes).unwrap();

    assert_eq!(
        stats.validation.partitioner_class,
        "org.apache.cassandra.dht.Murmur3Partitioner"
    );
    assert!(
        stats.validation.bloom_fp_chance > 0.0 && stats.validation.bloom_fp_chance < 1.0,
        "bloom FP chance should be between 0 and 1"
    );

    // Header should have column definitions matching our schema
    assert_eq!(
        stats.header.clustering_types.len(),
        1,
        "1 clustering column (ck int)"
    );
    assert_eq!(
        stats.header.regular_columns.len(),
        1,
        "1 regular column (val text)"
    );
}

#[test]
fn bloom_filter_matches_fixture_keys() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: bloom filter fixture test not generated");
        return;
    };

    let reader = open_fixture(&dir);

    // All inserted keys must pass the bloom filter (no false negatives)
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let (h1, h2) = dk.filter_hash();
        assert!(
            reader.bloom_filter().is_present(h1, h2),
            "Bloom filter must not have false negatives for {}",
            pk_str
        );
    }
}
