//! Cassandra compatibility tests — read SSTable fixtures generated by Cassandra.
//!
//! These tests read BTI SSTables produced by `tools/generate_sstable_fixtures.java`
//! and verify Ferrosa can correctly parse all component files. The fixture data
//! uses the schema:
//!
//!     CREATE TABLE test.fixture (pk text, ck int, val text, PRIMARY KEY (pk, ck))
//!
//! Fixture directories live under `tests/fixtures/` with standardized component
//! file names (Data.db, Partitions.db, etc.).

use std::fs;
use std::path::{Path, PathBuf};

use ferrosa_common::{DecoratedKey, PartitionKey};
use ferrosa_sstable::reader::{SSTableComponents, SSTableReader};
use ferrosa_sstable::statistics::read_statistics;
use ferrosa_sstable::toc;

/// Find the fixture directory, returning None if fixtures haven't been generated yet.
fn fixture_dir(name: &str) -> Option<PathBuf> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name);
    if dir.exists() {
        Some(dir)
    } else {
        None
    }
}

/// Load a component file from the fixture directory, returning its bytes.
fn load_component(dir: &Path, suffix: &str) -> Vec<u8> {
    let path = dir.join(suffix);
    fs::read(&path).unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e))
}

/// Open an SSTableReader from a fixture directory.
fn open_fixture(dir: &Path) -> SSTableReader<Vec<u8>> {
    let data = load_component(dir, "Data.db");
    let partitions = load_component(dir, "Partitions.db");
    let rows = load_component(dir, "Rows.db");
    let filter = load_component(dir, "Filter.db");
    let statistics = load_component(dir, "Statistics.db");
    let compression_info_path = dir.join("CompressionInfo.db");
    let compression_info = if compression_info_path.exists() {
        Some(fs::read(&compression_info_path).unwrap())
    } else {
        None
    };

    let components = SSTableComponents {
        data,
        partitions,
        rows,
        filter,
        compression_info,
        statistics,
    };

    SSTableReader::open(components).expect("Failed to open SSTable fixture")
}

#[test]
fn read_multi_partition_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: multi_partition fixture not generated. Run tools/generate_sstable_fixtures.java");
        return;
    };

    let reader = open_fixture(&dir);

    // Fixture has 5 partitions: alpha, bravo, charlie, delta, echo
    assert_eq!(reader.key_count(), 5, "expected 5 partitions");

    // Look up each known partition key
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let partition = match reader.get_partition(&dk) {
            Ok(p) => p,
            Err(e) => panic!("Error looking up {}: {}", pk_str, e),
        };
        assert!(
            partition.is_some(),
            "Partition {} should exist in fixture",
            pk_str
        );
        let partition = partition.unwrap();
        eprintln!(
            "Partition {}: key={:?}, deletion={{marked_for_delete_at={}, local_deletion_time={}}}, rows={}",
            pk_str,
            String::from_utf8_lossy(partition.key.key.as_bytes()),
            partition.deletion.marked_for_delete_at,
            partition.deletion.local_deletion_time,
            partition.rows.len()
        );
        assert_eq!(partition.key.key.as_bytes(), pk_str.as_bytes());
        assert!(partition.deletion.is_live());
        assert!(!partition.rows.is_empty(), "{} should have rows", pk_str);
    }
}

#[test]
fn read_single_partition_fixture() {
    let Some(dir) = fixture_dir("single_partition") else {
        eprintln!("Skipping: single_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"only-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'only-pk' should exist");
    let partition = partition.unwrap();
    assert_eq!(partition.rows.len(), 1, "should have exactly 1 row");
}

#[test]
fn read_wide_partition_fixture() {
    let Some(dir) = fixture_dir("wide_partition") else {
        eprintln!("Skipping: wide_partition fixture not generated");
        return;
    };

    let reader = open_fixture(&dir);

    assert_eq!(reader.key_count(), 1, "expected 1 partition");

    let dk = DecoratedKey::new(PartitionKey::from(b"wide-pk".as_slice()));
    let partition = reader.get_partition(&dk).unwrap();
    assert!(partition.is_some(), "Partition 'wide-pk' should exist");
    let partition = partition.unwrap();
    assert!(
        partition.rows.len() >= 50,
        "wide partition should have 50+ rows, got {}",
        partition.rows.len()
    );
}

#[test]
fn read_toc_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: TOC fixture not generated");
        return;
    };

    let toc_bytes = load_component(&dir, "TOC.txt");
    let entries = toc::read_toc(&toc_bytes).unwrap();
    assert!(entries.len() >= 6, "TOC should list at least 6 components");
}

#[test]
fn read_statistics_fixture() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: Statistics fixture not generated");
        return;
    };

    let stats_bytes = load_component(&dir, "Statistics.db");
    let stats = read_statistics(&stats_bytes).unwrap();

    assert_eq!(
        stats.validation.partitioner_class,
        "org.apache.cassandra.dht.Murmur3Partitioner"
    );
    assert!(
        stats.validation.bloom_fp_chance > 0.0 && stats.validation.bloom_fp_chance < 1.0,
        "bloom FP chance should be between 0 and 1"
    );

    // Header should have column definitions matching our schema
    assert_eq!(
        stats.header.clustering_types.len(),
        1,
        "1 clustering column (ck int)"
    );
    assert_eq!(
        stats.header.regular_columns.len(),
        1,
        "1 regular column (val text)"
    );
}

#[test]
/// Write-read roundtrip: ferrosa writer produces SSTables that ferrosa reader
/// can parse, for all cell types (normal, tombstone, expiring/TTL).
/// This validates the wire format matches Cassandra's Cell.Serializer spec.
fn ferrosa_write_read_roundtrip_all_cell_types() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec!["org.apache.cassandra.db.marshal.Int32Type".into()],
        static_columns: vec![],
        regular_columns: vec![(
            b"val".to_vec(),
            "org.apache.cassandra.db.marshal.UTF8Type".into(),
        )],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: true,
    };

    let timestamp = 1_000_100i64;

    // Three partitions: normal cell, tombstone cell, expiring cell (TTL)
    let partitions = vec![
        // 1. Normal cell
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"normal".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 1], // ck = 1
                cells: vec![(0, CellValue::live(b"hello".to_vec(), timestamp))],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
        // 2. Tombstone cell
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"tombstone".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 2],
                cells: vec![(0, CellValue::tombstone(timestamp, 1_700_000))],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
        // 3. Expiring cell (USING TTL 3600)
        Partition {
            key: DecoratedKey::new(PartitionKey::from(b"ttl_cell".as_slice())),
            deletion: DeletionTime::LIVE,
            static_row: None,
            rows: vec![Row {
                clustering: vec![0, 0, 0, 3],
                cells: vec![(
                    0,
                    CellValue::expiring(b"expires".to_vec(), timestamp, 3600, 1_700_000),
                )],
                deletion: DeletionTime::LIVE,
                primary_key_liveness: LivenessInfo::with_timestamp(timestamp),
            }],
        },
    ];

    let mut writer = SSTableWriter::new(options, header.clone());
    for p in &partitions {
        writer.add_partition(p).unwrap();
    }
    let output = writer.finish().unwrap();

    // Read back and verify each partition
    let mut reader = DataReader::new(&output.data, &header, 0);

    // 1. Normal cell
    let p = reader.read_partition().unwrap().expect("normal partition");
    assert_eq!(p.key.key.as_bytes(), b"normal");
    let cell = &p.rows[0].cells[0].1;
    assert!(!cell.is_tombstone());
    assert_eq!(
        cell.ttl,
        ferrosa_common::NO_TTL,
        "normal cell should have no TTL"
    );
    assert_eq!(cell.value.as_deref(), Some(b"hello".as_slice()));

    // 2. Tombstone cell
    let p = reader
        .read_partition()
        .unwrap()
        .expect("tombstone partition");
    assert_eq!(p.key.key.as_bytes(), b"tombstone");
    let cell = &p.rows[0].cells[0].1;
    assert!(cell.is_tombstone());
    assert_eq!(cell.timestamp, timestamp);
    assert_eq!(cell.local_deletion_time, 1_700_000);
    assert!(cell.value.is_none());

    // 3. Expiring cell
    let p = reader.read_partition().unwrap().expect("ttl partition");
    assert_eq!(p.key.key.as_bytes(), b"ttl_cell");
    let cell = &p.rows[0].cells[0].1;
    assert!(!cell.is_tombstone(), "expiring cell is not a tombstone");
    assert_eq!(cell.ttl, 3600, "TTL must survive roundtrip");
    assert_eq!(
        cell.local_deletion_time, 1_700_000,
        "LDT must survive roundtrip"
    );
    assert_eq!(cell.value.as_deref(), Some(b"expires".as_slice()));

    // No more partitions
    assert!(reader.read_partition().unwrap().is_none());
}

/// THE compatibility gate: read a `Data.db` produced by a real Cassandra 5.0
/// (`nb-big` format, uncompressed) for a table with non-frozen `list<int>`,
/// `set<text>`, and `map<text,int>` columns, and confirm ferrosa parses the
/// complex-column cells — proving Cassandra collection SSTables are importable.
///
/// This caught (and now guards against) a real byte-format bug: Cassandra
/// length-prefixes a collection element value even for a fixed-width element
/// type (`list<int>` values carry a `uvint(4)` prefix). It also exercises the
/// `HAS_COMPLEX_DELETION` path — a plain collection INSERT writes a complex
/// deletion before each collection column's cell count.
#[test]
fn read_real_cassandra_collections() {
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;

    let data = std::fs::read(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/cassandra_collections/Data.db"),
    )
    .expect("cassandra_collections fixture Data.db");

    // Storage column order is alphabetical: l, m, s. min_* only affect timestamp
    // VALUES (deltas are uvints either way), not byte alignment or the element
    // paths/values we assert here.
    let header = SerializationHeader {
        min_timestamp: 0,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![
            (
                b"l".to_vec(),
                "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)".into(),
            ),
            (
                b"m".to_vec(),
                "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.Int32Type)".into(),
            ),
            (
                b"s".to_vec(),
                "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)".into(),
            ),
        ],
    };

    let mut reader = DataReader::new(&data, &header, 0).with_complex_collections(true);
    let p = reader.read_partition().unwrap().expect("row1 partition");
    assert_eq!(p.key.key.as_bytes(), b"row1");
    let cells = &p.rows[0].cells;

    // A plain collection INSERT sets HAS_COMPLEX_DELETION: each collection column
    // carries a complex deletion, which the reader captures as a `path == None`
    // tombstone sentinel. Element assertions below skip those sentinels.
    for col in 0..=2 {
        assert!(
            cells
                .iter()
                .any(|(i, c)| *i == col && c.path.is_none() && c.is_tombstone()),
            "column {col} carries its captured complex-deletion sentinel"
        );
    }
    let elems = |col: u16| {
        cells
            .iter()
            .filter(move |(i, c)| *i == col && c.path.is_some())
    };

    // Column ordinals: l=0, m=1, s=2 (storage order).
    let list: Vec<i32> = elems(0)
        .map(|(_, c)| i32::from_be_bytes(c.value.as_deref().unwrap().try_into().unwrap()))
        .collect();
    assert_eq!(list, vec![10, 20, 30], "list<int> elements parse in order");

    let mut map: Vec<(String, i32)> = elems(1)
        .map(|(_, c)| {
            let k = String::from_utf8(c.path.clone().unwrap()).unwrap();
            let v = i32::from_be_bytes(c.value.as_deref().unwrap().try_into().unwrap());
            (k, v)
        })
        .collect();
    map.sort();
    assert_eq!(
        map,
        vec![("k1".into(), 1), ("k2".into(), 2)],
        "map<text,int> parses"
    );

    let mut set: Vec<String> = elems(2)
        .map(|(_, c)| String::from_utf8(c.path.clone().unwrap()).unwrap())
        .collect();
    set.sort();
    assert_eq!(
        set,
        vec!["a", "b", "c"],
        "set<text> elements parse from paths"
    );
}

/// Read a `Data.db` from a real Cassandra 5.0 with a NON-FROZEN UDT column
/// (`addr {street text, zip int}`). A non-frozen UDT is a complex column: each
/// field is a cell whose cell-path is a 2-byte big-endian field position. Proves
/// ferrosa parses real Cassandra UDT field cells (t_edf9fd15).
#[test]
fn read_real_cassandra_udt() {
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;

    let data = std::fs::read(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/cassandra_udt/Data.db"),
    )
    .expect("cassandra_udt fixture Data.db");

    // The reader only needs the column type's simple class name to be `UserType`
    // (to detect the complex UDT framing); it reads field cells as opaque
    // 2-byte-path + length-prefixed value. Field-value decoding happens in the
    // row-bridge assembly layer (CqlType::Udt), not here.
    let header = SerializationHeader {
        min_timestamp: 0,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![(
            b"a".to_vec(),
            "org.apache.cassandra.db.marshal.UserType(test,61646472,\
             73747265657400:org.apache.cassandra.db.marshal.UTF8Type,\
             7a697000:org.apache.cassandra.db.marshal.Int32Type)"
                .into(),
        )],
    };

    let mut reader = DataReader::new(&data, &header, 0).with_complex_collections(true);
    let p = reader.read_partition().unwrap().expect("row1 partition");
    assert_eq!(p.key.key.as_bytes(), b"row1");
    let cells = &p.rows[0].cells;

    // A UDT INSERT sets HAS_COMPLEX_DELETION -> captured sentinel (path=None).
    assert!(
        cells
            .iter()
            .any(|(_, c)| c.path.is_none() && c.is_tombstone()),
        "complex-deletion sentinel captured"
    );
    // Field cells: path = 2-byte position, value length-prefixed.
    let field = |pos: [u8; 2]| {
        cells
            .iter()
            .find(|(_, c)| c.path.as_deref() == Some(&pos[..]))
            .map(|(_, c)| c.value.clone().unwrap())
    };
    assert_eq!(
        field([0, 0]).as_deref(),
        Some(b"main".as_slice()),
        "field 0 = street 'main'"
    );
    assert_eq!(
        field([0, 1]).map(|v| i32::from_be_bytes(v.try_into().unwrap())),
        Some(12345),
        "field 1 = zip 12345"
    );
}

/// A non-frozen `list<int>` column stores each element as its own cell sharing
/// the column's storage index, distinguished by a 16-byte TimeUUID cell path
/// (Cassandra's complex-column layout). Two appended elements must round-trip
/// through the BTI writer + reader as two cells with their paths and values
/// intact — the increment-C hard gate before per-element collection writes.
#[test]
fn ferrosa_roundtrips_nonfrozen_list_complex_column() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![(
            b"l".to_vec(),
            "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)"
                .into(),
        )],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: false,
    };
    let ts = 1_000_100i64;

    // Two list<int> elements: value = 4-byte big-endian int (Int32Type is
    // fixed-width, so no length prefix), path = a 16-byte v1 TimeUUID.
    let path_a = {
        let mut p = [0u8; 16];
        p[0..4].copy_from_slice(&10u32.to_be_bytes());
        p[6] = 0x10; // version 1
        p[8] = 0x80; // variant
        p.to_vec()
    };
    let path_b = {
        let mut p = [0u8; 16];
        p[0..4].copy_from_slice(&20u32.to_be_bytes());
        p[6] = 0x10;
        p[8] = 0x80;
        p.to_vec()
    };
    let cell_a = CellValue::live(10i32.to_be_bytes().to_vec(), ts).with_path(path_a.clone());
    let cell_b = CellValue::live(20i32.to_be_bytes().to_vec(), ts).with_path(path_b.clone());

    let partition = Partition {
        key: DecoratedKey::new(PartitionKey::from(b"pk".as_slice())),
        deletion: DeletionTime::LIVE,
        static_row: None,
        rows: vec![Row {
            clustering: vec![],
            cells: vec![(0, cell_a), (0, cell_b)],
            deletion: DeletionTime::LIVE,
            primary_key_liveness: LivenessInfo::with_timestamp(ts),
        }],
    };

    let mut writer = SSTableWriter::new(options, header.clone()).with_complex_collections(true);
    writer.add_partition(&partition).unwrap();
    let output = writer.finish().unwrap();

    let mut reader = DataReader::new(&output.data, &header, 0).with_complex_collections(true);
    let p = reader.read_partition().unwrap().expect("list partition");
    let cells = &p.rows[0].cells;
    assert_eq!(cells.len(), 2, "two element cells round-trip");
    assert!(cells.iter().all(|(idx, _)| *idx == 0), "same column index");
    assert_eq!(cells[0].1.path.as_deref(), Some(path_a.as_slice()));
    assert_eq!(cells[0].1.value.as_deref(), Some(&10i32.to_be_bytes()[..]));
    assert_eq!(cells[1].1.path.as_deref(), Some(path_b.as_slice()));
    assert_eq!(cells[1].1.value.as_deref(), Some(&20i32.to_be_bytes()[..]));
    assert!(reader.read_partition().unwrap().is_none());
}

/// A complex-column deletion (represented as a `path=None` tombstone sentinel)
/// round-trips through the writer + reader: the writer sets HAS_COMPLEX_DELETION
/// and emits the DeletionTime; the reader captures it back as the sentinel,
/// alongside the surviving element cells.
#[test]
fn ferrosa_roundtrips_complex_column_deletion() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 100,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![(
            b"l".to_vec(),
            "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)"
                .into(),
        )],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: false,
    };

    // Collection deletion at ts=499 (a `path=None` tombstone), one element at ts=500.
    let deletion = CellValue::tombstone(499, 1_700_000);
    let mut lp = [0u8; 16];
    lp[0..4].copy_from_slice(&7u32.to_be_bytes());
    lp[6] = 0x10;
    lp[8] = 0x80;
    let elem = CellValue::live(55i32.to_be_bytes().to_vec(), 500).with_path(lp.to_vec());

    let partition = Partition {
        key: DecoratedKey::new(PartitionKey::from(b"pk".as_slice())),
        deletion: DeletionTime::LIVE,
        static_row: None,
        rows: vec![Row {
            clustering: vec![],
            cells: vec![(0, deletion), (0, elem)],
            deletion: DeletionTime::LIVE,
            primary_key_liveness: LivenessInfo::with_timestamp(500),
        }],
    };

    let mut writer = SSTableWriter::new(options, header.clone()).with_complex_collections(true);
    writer.add_partition(&partition).unwrap();
    let output = writer.finish().unwrap();

    let mut reader = DataReader::new(&output.data, &header, 0).with_complex_collections(true);
    let p = reader.read_partition().unwrap().expect("partition");
    let cells = &p.rows[0].cells;

    let sentinel = cells
        .iter()
        .find(|(_, c)| c.path.is_none())
        .expect("complex-deletion sentinel round-trips");
    assert!(sentinel.1.is_tombstone());
    assert_eq!(sentinel.1.timestamp, 499, "deletion marked_for_delete_at");

    let element = cells
        .iter()
        .find(|(_, c)| c.path.is_some())
        .expect("element cell round-trips");
    assert_eq!(element.1.value.as_deref(), Some(&55i32.to_be_bytes()[..]));
    assert_eq!(element.1.path.as_deref(), Some(&lp[..]));
}

/// `set<text>` (element = path, empty value), `map<text,int>` (key = path,
/// value = int), and a set-element tombstone (remove) all round-trip through
/// the complex-column layout — with the two complex columns in the same row.
#[test]
fn ferrosa_roundtrips_nonfrozen_set_map_and_tombstone() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![
            (
                b"s".to_vec(),
                "org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.UTF8Type)"
                    .into(),
            ),
            (
                b"m".to_vec(),
                "org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.Int32Type)".into(),
            ),
        ],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: false,
    };
    let ts = 1_000_100i64;

    // set col 0: element "a" live (empty value, path="a"), element "b" removed (tombstone, path="b")
    let set_a = CellValue::live(Vec::new(), ts).with_path(b"a".to_vec());
    let set_b = CellValue::tombstone(ts, 1_700_000).with_path(b"b".to_vec());
    // map col 1: key "k" -> 7
    let map_k = CellValue::live(7i32.to_be_bytes().to_vec(), ts).with_path(b"k".to_vec());

    let partition = Partition {
        key: DecoratedKey::new(PartitionKey::from(b"pk".as_slice())),
        deletion: DeletionTime::LIVE,
        static_row: None,
        rows: vec![Row {
            clustering: vec![],
            cells: vec![(0, set_a), (0, set_b), (1, map_k)],
            deletion: DeletionTime::LIVE,
            primary_key_liveness: LivenessInfo::with_timestamp(ts),
        }],
    };

    let mut writer = SSTableWriter::new(options, header.clone()).with_complex_collections(true);
    writer.add_partition(&partition).unwrap();
    let output = writer.finish().unwrap();

    let mut reader = DataReader::new(&output.data, &header, 0).with_complex_collections(true);
    let p = reader.read_partition().unwrap().expect("partition");
    let cells = &p.rows[0].cells;
    // 2 set cells (col 0) + 1 map cell (col 1)
    let set_cells: Vec<_> = cells.iter().filter(|(i, _)| *i == 0).collect();
    let map_cells: Vec<_> = cells.iter().filter(|(i, _)| *i == 1).collect();
    assert_eq!(set_cells.len(), 2, "set element + tombstone both present");
    assert_eq!(map_cells.len(), 1);

    // set element "a": live, empty value, path "a".
    let a = set_cells
        .iter()
        .find(|(_, c)| c.path.as_deref() == Some(b"a"))
        .unwrap();
    assert!(!a.1.is_tombstone());
    assert_eq!(
        a.1.value.as_deref(),
        Some(&[][..]),
        "set element value is empty"
    );
    // set element "b": tombstone, path "b".
    let b = set_cells
        .iter()
        .find(|(_, c)| c.path.as_deref() == Some(b"b"))
        .unwrap();
    assert!(
        b.1.is_tombstone(),
        "removed set element round-trips as a tombstone"
    );
    // map entry: key "k" (path), value 7 (int).
    assert_eq!(map_cells[0].1.path.as_deref(), Some(b"k".as_slice()));
    assert_eq!(
        map_cells[0].1.value.as_deref(),
        Some(&7i32.to_be_bytes()[..])
    );
}

/// A projected read (SELECT of a subset of columns) over a table with a complex
/// column must skip/read the complex-column framing correctly — otherwise the
/// parse position drifts. Projecting the list column returns its element cells;
/// projecting the scalar column skips the list without corruption.
#[test]
fn ferrosa_projected_read_over_complex_column() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::*;
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: 0,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.UTF8Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![
            (
                b"l".to_vec(),
                "org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)".into(),
            ),
            (b"n".to_vec(), "org.apache.cassandra.db.marshal.Int32Type".into()),
        ],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: false,
    };
    let ts = 1_000_100i64;

    let mut lp = [0u8; 16];
    lp[0..4].copy_from_slice(&5u32.to_be_bytes());
    lp[6] = 0x10;
    lp[8] = 0x80;
    let list_elem = CellValue::live(99i32.to_be_bytes().to_vec(), ts).with_path(lp.to_vec());
    let scalar = CellValue::live(42i32.to_be_bytes().to_vec(), ts);

    let partition = Partition {
        key: DecoratedKey::new(PartitionKey::from(b"pk".as_slice())),
        deletion: DeletionTime::LIVE,
        static_row: None,
        rows: vec![Row {
            clustering: vec![],
            cells: vec![(0, list_elem), (1, scalar)],
            deletion: DeletionTime::LIVE,
            primary_key_liveness: LivenessInfo::with_timestamp(ts),
        }],
    };

    let mut writer = SSTableWriter::new(options, header.clone()).with_complex_collections(true);
    writer.add_partition(&partition).unwrap();
    let output = writer.finish().unwrap();

    // Project only the scalar column (ordinal 1): the list complex framing must
    // be skipped without drift.
    let mut reader = DataReader::new(&output.data, &header, 0).with_complex_collections(true);
    let p = reader
        .read_partition_projected(&[1])
        .unwrap()
        .expect("partition");
    let cells = &p.rows[0].cells;
    assert_eq!(cells.len(), 1, "only the projected scalar column");
    assert_eq!(cells[0].0, 1);
    assert_eq!(cells[0].1.value.as_deref(), Some(&42i32.to_be_bytes()[..]));

    // Project only the list column (ordinal 0): its element cell comes back.
    let mut reader = DataReader::new(&output.data, &header, 0).with_complex_collections(true);
    let p = reader
        .read_partition_projected(&[0])
        .unwrap()
        .expect("partition");
    let cells = &p.rows[0].cells;
    assert_eq!(cells.len(), 1, "one list element");
    assert_eq!(cells[0].0, 0);
    assert_eq!(cells[0].1.path.as_deref(), Some(&lp[..]));
    assert_eq!(cells[0].1.value.as_deref(), Some(&99i32.to_be_bytes()[..]));
}

#[test]
/// The compat test infrastructure files must exist before a Docker run is
/// attempted.  This test acts as a quick smoke-check: if the files are
/// missing the CI step that calls `compat_test.sh` would fail with a
/// confusing error.
fn cassandra_reader_container_starts() {
    // docker-compose.yml
    assert!(
        std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../tests/sstable-compat/docker-compose.yml"
        ))
        .exists(),
        "tests/sstable-compat/docker-compose.yml must exist"
    );

    // compat_test.sh
    assert!(
        std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../tests/sstable-compat/compat_test.sh"
        ))
        .exists(),
        "tests/sstable-compat/compat_test.sh must exist"
    );

    // write-sstable Cargo.toml
    assert!(
        std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../tests/sstable-compat/Cargo.toml"
        ))
        .exists(),
        "tests/sstable-compat/Cargo.toml must exist"
    );

    // write_sstable.rs binary source
    assert!(
        std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../tests/sstable-compat/src/write_sstable.rs"
        ))
        .exists(),
        "tests/sstable-compat/src/write_sstable.rs must exist"
    );
}

#[test]
/// Rust-side round-trip for all simple CQL types through SSTableWriter +
/// DataReader.  This validates the on-disk encoding without Docker.  The
/// Cassandra-side import is handled by `compat_test.sh`.
///
/// Schema:
///   compat.simple_types (id int PRIMARY KEY, v_text text, v_bool boolean,
///     v_bigint bigint, v_float float, v_double double, v_blob blob)
fn sstable_compat_simple_types() {
    use ferrosa_common::CellValue;
    use ferrosa_sstable::data::DataReader;
    use ferrosa_sstable::statistics::SerializationHeader;
    use ferrosa_sstable::types::{DeletionTime, LivenessInfo, Row};
    use ferrosa_sstable::writer::{SSTableWriter, WriteOptions};

    // Column index -> type mapping (same ordering used in write_sstable.rs):
    //   0 v_text   UTF8Type
    //   1 v_bool   BooleanType
    //   2 v_bigint LongType
    //   3 v_float  FloatType
    //   4 v_double DoubleType
    //   5 v_blob   BytesType
    let header = SerializationHeader {
        min_timestamp: 1_000_000,
        min_local_deletion_time: i32::MAX,
        min_ttl: 0,
        max_timestamp: i64::MAX,
        key_type: "org.apache.cassandra.db.marshal.Int32Type".into(),
        clustering_types: vec![],
        static_columns: vec![],
        regular_columns: vec![
            (
                b"v_text".to_vec(),
                "org.apache.cassandra.db.marshal.UTF8Type".into(),
            ),
            (
                b"v_bool".to_vec(),
                "org.apache.cassandra.db.marshal.BooleanType".into(),
            ),
            (
                b"v_bigint".to_vec(),
                "org.apache.cassandra.db.marshal.LongType".into(),
            ),
            (
                b"v_float".to_vec(),
                "org.apache.cassandra.db.marshal.FloatType".into(),
            ),
            (
                b"v_double".to_vec(),
                "org.apache.cassandra.db.marshal.DoubleType".into(),
            ),
            (
                b"v_blob".to_vec(),
                "org.apache.cassandra.db.marshal.BytesType".into(),
            ),
        ],
    };
    let options = WriteOptions {
        compression: None,
        bloom_fp_chance: 0.01,
        chunk_size: 65536,
        verify_output: true,
    };

    let ts = 1_743_120_000_000_000i64;

    // Partition key: id = 1 encoded as big-endian i32.
    let pk_bytes: [u8; 4] = 1i32.to_be_bytes();
    let partition = ferrosa_sstable::types::Partition {
        key: ferrosa_common::DecoratedKey::new(ferrosa_common::PartitionKey::from(
            pk_bytes.as_slice(),
        )),
        deletion: DeletionTime::LIVE,
        static_row: None,
        rows: vec![Row {
            clustering: vec![],
            cells: vec![
                (0, CellValue::live(b"hello".to_vec(), ts)),
                (1, CellValue::live(vec![0x01], ts)), // boolean true
                (2, CellValue::live(42i64.to_be_bytes().to_vec(), ts)),
                (
                    3,
                    CellValue::live((3.25f32).to_bits().to_be_bytes().to_vec(), ts),
                ),
                (
                    4,
                    CellValue::live((2.75f64).to_bits().to_be_bytes().to_vec(), ts),
                ),
                (5, CellValue::live(vec![0xDE, 0xAD, 0xBE, 0xEF], ts)),
            ],
            deletion: DeletionTime::LIVE,
            primary_key_liveness: LivenessInfo::with_timestamp(ts),
        }],
    };

    let mut writer = SSTableWriter::new(options, header.clone());
    writer.add_partition(&partition).unwrap();
    let output = writer.finish().unwrap();

    // Read back with DataReader and verify every cell.
    let mut reader = DataReader::new(&output.data, &header, 0);
    let p = reader
        .read_partition()
        .unwrap()
        .expect("expected one partition");

    assert_eq!(p.key.key.as_bytes(), pk_bytes.as_slice(), "partition key");
    assert!(p.deletion.is_live(), "partition deletion must be live");
    assert_eq!(p.rows.len(), 1, "one row");

    let row = &p.rows[0];
    assert!(row.clustering.is_empty(), "no clustering columns");
    assert_eq!(row.primary_key_liveness.timestamp, ts);
    assert_eq!(row.cells.len(), 6, "six regular columns");

    // col 0: v_text = "hello"
    let (idx, ref cell) = row.cells[0];
    assert_eq!(idx, 0);
    assert!(cell.is_live());
    assert_eq!(cell.value.as_deref(), Some(b"hello".as_slice()), "v_text");

    // col 1: v_bool = 0x01 (true)
    let (idx, ref cell) = row.cells[1];
    assert_eq!(idx, 1);
    assert_eq!(cell.value.as_deref(), Some([0x01].as_slice()), "v_bool");

    // col 2: v_bigint = 42
    let (idx, ref cell) = row.cells[2];
    assert_eq!(idx, 2);
    let bigint_bytes = cell.value.as_deref().expect("v_bigint value");
    assert_eq!(
        i64::from_be_bytes(bigint_bytes.try_into().unwrap()),
        42i64,
        "v_bigint"
    );

    // col 3: v_float = 3.14
    let (idx, ref cell) = row.cells[3];
    assert_eq!(idx, 3);
    let float_bytes = cell.value.as_deref().expect("v_float value");
    let float_bits = u32::from_be_bytes(float_bytes.try_into().unwrap());
    assert!(
        (f32::from_bits(float_bits) - 3.25f32).abs() < 1e-5,
        "v_float should be ~3.25, got {}",
        f32::from_bits(float_bits)
    );

    // col 4: v_double = 2.718281828
    let (idx, ref cell) = row.cells[4];
    assert_eq!(idx, 4);
    let double_bytes = cell.value.as_deref().expect("v_double value");
    let double_bits = u64::from_be_bytes(double_bytes.try_into().unwrap());
    assert!(
        (f64::from_bits(double_bits) - 2.75f64).abs() < 1e-9,
        "v_double should be ~2.75, got {}",
        f64::from_bits(double_bits)
    );

    // col 5: v_blob = 0xDEADBEEF
    let (idx, ref cell) = row.cells[5];
    assert_eq!(idx, 5);
    assert_eq!(
        cell.value.as_deref(),
        Some([0xDE, 0xAD, 0xBE, 0xEF].as_slice()),
        "v_blob"
    );

    // No more partitions.
    assert!(reader.read_partition().unwrap().is_none());
}

#[test]
/// Read SSTable fixtures generated by Cassandra's CQLSSTableWriter.
/// These test that ferrosa can read SSTables produced by real Cassandra code.
/// Run `tests/sstable-compat/generate.sh` to create the fixtures.
fn read_cassandra_generated_normal_cells() {
    let Some(dir) = fixture_dir("cassandra_generated/normal_cells") else {
        eprintln!(
            "Skipping: Cassandra-generated fixtures not found. Run tests/sstable-compat/generate.sh"
        );
        return;
    };

    // Find the actual SSTable directory (Cassandra puts them in a subdirectory)
    let sstable_dirs: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .collect();

    if sstable_dirs.is_empty() {
        // Files might be directly in the directory
        let reader = open_fixture(&dir);
        assert!(
            reader.key_count() >= 3,
            "expected at least 3 partitions (alpha, bravo, charlie)"
        );
    } else {
        // Cassandra nests SSTables in subdirectories
        for sub in sstable_dirs {
            let path = sub.path();
            if std::fs::read_dir(&path).unwrap().any(|e| {
                e.unwrap()
                    .file_name()
                    .to_string_lossy()
                    .ends_with("-Data.db")
            }) {
                eprintln!("Reading Cassandra SSTable from {:?}", path);
                // TODO: Cassandra uses different file naming (e.g., nb-1-big-Data.db)
                // Need to adapt the reader for Cassandra's file naming convention
            }
        }
    }
}

#[test]
fn read_cassandra_generated_ttl_cells() {
    let Some(dir) = fixture_dir("cassandra_generated/ttl_cells") else {
        eprintln!(
            "Skipping: Cassandra TTL fixtures not found. Run tests/sstable-compat/generate.sh"
        );
        return;
    };

    // When fixtures exist, verify expiring cells are parsed with correct TTL
    eprintln!("Cassandra TTL fixture directory exists at {:?}", dir);
    // Full parsing test will be added once fixture naming is standardized
}

#[test]
fn bloom_filter_matches_fixture_keys() {
    let Some(dir) = fixture_dir("multi_partition") else {
        eprintln!("Skipping: bloom filter fixture test not generated");
        return;
    };

    let reader = open_fixture(&dir);

    // All inserted keys must pass the bloom filter (no false negatives)
    for pk_str in &["alpha", "bravo", "charlie", "delta", "echo"] {
        let dk = DecoratedKey::new(PartitionKey::from(pk_str.as_bytes()));
        let (h1, h2) = dk.filter_hash();
        assert!(
            reader.bloom_filter().is_present(h1, h2),
            "Bloom filter must not have false negatives for {}",
            pk_str
        );
    }
}
