//! Regenerates the T-035 golden SSTable corpus.
//!
//! Destructive (overwrites `tests/golden/`) and **never runs in normal
//! CI**: the rewrite only happens when `FERROSA_REGEN_GOLDEN` is set.
//! Without it, this test still performs a real check — that
//! `tests/golden/manifest.txt` names exactly the cases `support::golden`
//! declares, in order — so `cargo test` never silently no-ops here; it just
//! doesn't touch the corpus.
//!
//! Regenerate with:
//!   FERROSA_REGEN_GOLDEN=1 cargo test -p ferrosa-sstable --test golden_regen -- --nocapture

mod support;

use support::golden::{
    build_case, format_manifest_entry, golden_dir, manifest_path, sha256_hex, write_case_to_disk,
    write_options, CASES,
};
use support::legacy_writer::{legacy_write, legacy_write_file_backed};

#[test]
fn golden_regen_writes_corpus_when_requested() {
    if std::env::var("FERROSA_REGEN_GOLDEN").is_ok() {
        regenerate();
    }

    // Always-on: the manifest on disk names exactly today's CASES, in order.
    // This keeps the test meaningful (a real assertion, not a bare early
    // return) whether or not FERROSA_REGEN_GOLDEN was set.
    let manifest_text = std::fs::read_to_string(manifest_path()).unwrap_or_else(|e| {
        panic!(
            "tests/golden/manifest.txt missing or unreadable ({e}); run \
             `FERROSA_REGEN_GOLDEN=1 cargo test -p ferrosa-sstable --test golden_regen -- --nocapture` once"
        )
    });
    let manifest_cases: Vec<&str> = manifest_text
        .lines()
        .filter_map(|line| line.strip_prefix("case: "))
        .collect();
    let expected_cases: Vec<&str> = CASES.iter().map(|c| c.name).collect();
    assert_eq!(
        manifest_cases, expected_cases,
        "tests/golden/manifest.txt is out of sync with CASES in tests/support/golden.rs; \
         run FERROSA_REGEN_GOLDEN=1 to regenerate"
    );
}

fn regenerate() {
    std::fs::create_dir_all(golden_dir()).expect("create tests/golden");
    let mut manifest = String::from(
        "# Golden SSTable corpus for ferrosa-sstable T-035.\n\
         # Regenerated by `FERROSA_REGEN_GOLDEN=1 cargo test -p ferrosa-sstable --test golden_regen`.\n\
         # Do not hand-edit: `oracle_golden_reproduction` (tests/oracle.rs) checks these files\n\
         # reproduce byte-for-byte from CASES in tests/support/golden.rs.\n\n",
    );

    for spec in CASES {
        let (header, partitions) = build_case(spec);
        let options = write_options(spec);

        let bytes = if spec.file_backed {
            let dir =
                tempfile::tempdir().unwrap_or_else(|e| panic!("case {}: tempdir: {e}", spec.name));
            // T-038: parent of this path is the staging directory the writer
            // opens Data.db in — must match `staging_dir` below.
            let raw_data_path = dir.path().join("staging").join("Data.raw");
            legacy_write_file_backed(
                &partitions,
                &header,
                options,
                dir.path().join("staging"),
                raw_data_path,
            )
            .unwrap_or_else(|e| panic!("case {}: file-backed write failed: {e}", spec.name))
        } else {
            legacy_write(&partitions, &header, options)
                .unwrap_or_else(|e| panic!("case {}: in-memory write failed: {e}", spec.name))
        };

        let digests: Vec<(&str, String)> = bytes
            .named_components()
            .into_iter()
            .map(|(name, data)| (name, sha256_hex(data)))
            .collect();
        write_case_to_disk(spec.name, &bytes);
        manifest.push_str(&format_manifest_entry(spec, &digests));
    }

    std::fs::write(manifest_path(), manifest).expect("write tests/golden/manifest.txt");
    eprintln!(
        "golden_regen: wrote {} case(s) to {}",
        CASES.len(),
        golden_dir().display()
    );
}
