<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>FerrosJepsen</AssemblyName>
    <RootNamespace>FerrosJepsen</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" Version="3.20.1" />
  </ItemGroup>
</Project>
