#!/bin/sh
set -eu

if [ -n "${FLY_PRIVATE_IP:-}" ]; then
  export FERROSA_INTERNODE_BROADCAST="${FERROSA_INTERNODE_BROADCAST:-[${FLY_PRIVATE_IP}]:17000}"
  export FERROSA_CQL_BROADCAST="${FERROSA_CQL_BROADCAST:-[${FLY_PRIVATE_IP}]:9042}"
fi

if [ -n "${AWS_ENDPOINT_URL_S3:-}" ]; then
  export FERROSA_S3_ENDPOINT="${FERROSA_S3_ENDPOINT:-${AWS_ENDPOINT_URL_S3}}"
fi
if [ -n "${BUCKET_NAME:-}" ]; then
  export FERROSA_S3_BUCKET="${FERROSA_S3_BUCKET:-${BUCKET_NAME}}"
fi
if [ -n "${AWS_REGION:-}" ]; then
  export FERROSA_S3_REGION="${FERROSA_S3_REGION:-${AWS_REGION}}"
fi
if [ -n "${AWS_ACCESS_KEY_ID:-}" ]; then
  export FERROSA_S3_ACCESS_KEY_ID="${FERROSA_S3_ACCESS_KEY_ID:-${AWS_ACCESS_KEY_ID}}"
fi
if [ -n "${AWS_SECRET_ACCESS_KEY:-}" ]; then
  export FERROSA_S3_SECRET_ACCESS_KEY="${FERROSA_S3_SECRET_ACCESS_KEY:-${AWS_SECRET_ACCESS_KEY}}"
fi

exec "$@"
